version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - .:/app
    command: sh -c "bun run migrate:latest && bun start"

volumes:
  postgres_data:
